/***************************************************************************//**
* @file app.c
* @version 1.0.0
*******************************************************************************
* # License
* <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
*******************************************************************************
*
* SPDX-License-Identifier: Zlib
*
* The licensor of this software is Silicon Laboratories Inc.
*
* This software is provided \'as-is\', without any express or implied
* warranty. In no event will the authors be held liable for any damages
* arising from the use of this software.
*
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it
* freely, subject to the following restrictions:
*
* 1. The origin of this software must not be misrepresented; you must not
*    claim that you wrote the original software. If you use this software
*    in a product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
* 3. This notice may not be removed or altered from any source distribution.
*
*******************************************************************************
* # Experimental Quality
* This code has not been formally tested and is provided as-is. It is not
* suitable for production environments. In addition, this code will not be
* maintained and there may be no bug maintenance planned for these resources.
* Silicon Labs may update projects from time to time.
******************************************************************************/

#include <stdio.h>
#include "em_common.h"
#include "sl_app_assert.h"
#include "sl_bluetooth.h"
#include "gatt_db.h"
#include "app.h"
#include "sl_sensor_hall.h"
#include "em_msc.h"
#include "em_gpio.h"
#include "em_cmu.h"
#include "em_emu.h"
#include "sl_status.h"
#include "nvm3.h"
#include "nvm3_default.h"
#include "gpiointerrupt.h"
#include "sl_emlib_gpio_init_BTN0_config.h"
#include "sl_emlib_gpio_init_FLASH_WRITE_INDICATOR_config.h"
#include "sl_emlib_gpio_init_SLEEP_INDICATOR_config.h"


// The advertising set handle allocated from Bluetooth stack.
static uint8_t advertising_set_handle = 0xff;

// Static variable to store request to sample hall sensor
// Request generated by GPIO interrupt on each BTN0 press
static bool hall_sensor_request;

// Static handle for the nvm3 object storing the latest hall sensor sample
static nvm3_ObjectKey_t sample_object_key = 0xA5A5;

// Static counter tracking how many hall sensor samples have been recorded
static uint32_t sample_count = 0;

typedef struct {
  float field_strength;
  uint32_t id;
  bool alert;
  bool tamper;
} hall_sensor_sample_t;

// Set request signal to sample hall sensor
// This request is processed in app_process_action()
void app_request_hall_sensor(uint8_t intNo) {
  sl_app_assert(intNo == 0);
  hall_sensor_request = true;
}

/**************************************************************************//**
 * Application Init.
 *****************************************************************************/
SL_WEAK void app_init(void)
{
  /////////////////////////////////////////////////////////////////////////////
  // Put your additional application init code here!                         //
  // This is called once during start-up.                                    //
  /////////////////////////////////////////////////////////////////////////////

  hall_sensor_sample_t sample;

  // Load the last stored sensor sample
  Ecode_t err = nvm3_readData(
      nvm3_defaultHandle,
      sample_object_key,
      &sample,
      sizeof(hall_sensor_sample_t));
  // If a previously stored sample was found, display it and update the count
  if (err == ECODE_NVM3_OK) {
    printf(
        "Stored Sample %lu\r\n"
        "  field_strength: %lu\r\n"
        "  alert: %u\r\n"
        "  tamper: %u\r\n\r\n",
        sample.id,
        (uint32_t) sample.field_strength,
        sample.alert,
        sample.tamper);
    // update count value
    sample_count = sample.id + 1;
  } else {
    printf(
        "Failed to find a previously stored sample.\r\n"
        "NVM3 Error 0x%lx returned.\r\n"
        "Check nvm3.h for details about specific error codes.\r\n\r\n", err);
  }

  // Enable and configure hall effect sensor
  sl_sensor_hall_init();

  /* Enable and configure GPIO Pin interrupt
   * Interrupt 0 is registered to trigger when BTN0 is pressed and
   * calls app_request_hall_sensor
   */
  GPIOINT_Init();
  GPIOINT_CallbackRegister(0, app_request_hall_sensor);
  GPIO_ExtIntConfig(
      SL_EMLIB_GPIO_INIT_BTN0_PORT,
      SL_EMLIB_GPIO_INIT_BTN0_PIN,
      0,
      false,
      true,
      true);
  GPIO_IntEnable(1 << 0);
}

/**************************************************************************//**
 * Application Process Action.
 *****************************************************************************/
SL_WEAK void app_process_action(void)
{
  /////////////////////////////////////////////////////////////////////////////
  // Put your additional application code here!                              //
  // This is called infinitely.                                              //
  // Do not call blocking functions from here!                               //
  /////////////////////////////////////////////////////////////////////////////

  hall_sensor_sample_t sample;

  // Request is generated when BTN0 is pressed in app_request_hall_sensor
  if (hall_sensor_request) {
    // Clear request for next BTN0 press
    hall_sensor_request = false;

    // Increment sample id to keep track of how many samples have been taken
    sample.id = sample_count++;

    // Sample i2c and store data
    sl_sensor_hall_get(&sample.field_strength, &sample.alert, &sample.tamper);

    // Start GPIO high pulse for flash write duration
    GPIO_PinOutSet(
        SL_EMLIB_GPIO_INIT_FLASH_WRITE_INDICATOR_PORT,
        SL_EMLIB_GPIO_INIT_FLASH_WRITE_INDICATOR_PIN);

    // Write field strength value to flash
    nvm3_writeData(
        nvm3_defaultHandle,
        sample_object_key,
        &sample,
        sizeof(hall_sensor_sample_t));

    // End GPIO high pulse for flash write duration
    GPIO_PinOutClear(
        SL_EMLIB_GPIO_INIT_FLASH_WRITE_INDICATOR_PORT,
        SL_EMLIB_GPIO_INIT_FLASH_WRITE_INDICATOR_PIN);

    // Report saved sensor sample to VCOM port
    printf(
        "New Sample %lu\r\n"
        "  field_strength: %lu\r\n"
        "  alert: %u\r\n"
        "  tamper: %u\r\n",
        sample.id,
        (uint32_t) sample.field_strength,
        sample.alert,
        sample.tamper);
  }
  // Start GPIO high pulse for sleep duration
  // Cleared in modified em_emu.c and em_emu.h (EMU_EnterEM1/EM2)
  GPIO_PinOutSet(
      SL_EMLIB_GPIO_INIT_SLEEP_INDICATOR_PORT,
      SL_EMLIB_GPIO_INIT_SLEEP_INDICATOR_PIN);
}

/**************************************************************************//**
 * Bluetooth stack event handler.
 * This overrides the dummy weak implementation.
 *
 * @param[in] evt Event coming from the Bluetooth stack.
 *****************************************************************************/
void sl_bt_on_event(sl_bt_msg_t *evt)
{
  sl_status_t sc;
  bd_addr address;
  uint8_t address_type;
  uint8_t system_id[8];

  switch (SL_BT_MSG_ID(evt->header)) {
    // -------------------------------
    // This event indicates the device has started and the radio is ready.
    // Do not call any stack command before receiving this boot event!
    case sl_bt_evt_system_boot_id:

      // Extract unique ID from BT Address.
      sc = sl_bt_system_get_identity_address(&address, &address_type);
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to get Bluetooth address\n",
                    (int)sc);

      // Pad and reverse unique ID to get System ID.
      system_id[0] = address.addr[5];
      system_id[1] = address.addr[4];
      system_id[2] = address.addr[3];
      system_id[3] = 0xFF;
      system_id[4] = 0xFE;
      system_id[5] = address.addr[2];
      system_id[6] = address.addr[1];
      system_id[7] = address.addr[0];

      sc = sl_bt_gatt_server_write_attribute_value(gattdb_system_id,
                                                   0,
                                                   sizeof(system_id),
                                                   system_id);
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to write attribute\n",
                    (int)sc);

      // Create an advertising set.
      sc = sl_bt_advertiser_create_set(&advertising_set_handle);
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to create advertising set\n",
                    (int)sc);

      // Set advertising interval to 100ms.
      sc = sl_bt_advertiser_set_timing(
        advertising_set_handle,
        160, // min. adv. interval (milliseconds * 1.6)
        160, // max. adv. interval (milliseconds * 1.6)
        0,   // adv. duration
        0);  // max. num. adv. events
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to set advertising timing\n",
                    (int)sc);
      // Start general advertising and enable connections.
      sc = sl_bt_advertiser_start(
        advertising_set_handle,
        advertiser_general_discoverable,
        advertiser_connectable_scannable);
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to start advertising\n",
                    (int)sc);
      break;

    // -------------------------------
    // This event indicates that a new connection was opened.
    case sl_bt_evt_connection_opened_id:
      break;

    // -------------------------------
    // This event indicates that a connection was closed.
    case sl_bt_evt_connection_closed_id:
      // Restart advertising after client has disconnected.
      sc = sl_bt_advertiser_start(
        advertising_set_handle,
        advertiser_general_discoverable,
        advertiser_connectable_scannable);
      sl_app_assert(sc == SL_STATUS_OK,
                    "[E: 0x%04x] Failed to start advertising\n",
                    (int)sc);
      break;

    ///////////////////////////////////////////////////////////////////////////
    // Add additional event handlers here as your application requires!      //
    ///////////////////////////////////////////////////////////////////////////

    // -------------------------------
    // Default event handler.
    default:
      break;
  }
}
