/***************************************************************************//**
 * @file app.c
 * @version 1.0.0
 *******************************************************************************
 * # License
 * <b>Copyright 2020 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided \'as-is\', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 *******************************************************************************
 * # Experimental Quality
 * This code has not been formally tested and is provided as-is. It is not
 * suitable for production environments. In addition, this code will not be
 * maintained and there may be no bug maintenance planned for these resources.
 * Silicon Labs may update projects from time to time.
 ******************************************************************************/
#include "em_common.h"
#include "em_gpio.h"
#include "em_cmu.h"
#include "em_emu.h"

#include "app_assert.h"
#include "sl_bluetooth.h"
#include "gatt_db.h"
#include "app.h"
#include "sl_sensor_hall.h"

#include "sl_status.h"
#include "nvm3.h"
#include "nvm3_default.h"
#include "sl_simple_button_instances.h"
#include "app_log.h"

#define FLASH_WRITE_INDICATOR_PORT   gpioPortA
#define FLASH_WRITE_INDICATOR_PIN    8
#define SLEEP_INDICATOR_PORT         gpioPortC
#define SLEEP_INDICATOR_PIN          6

// The advertising set handle allocated from Bluetooth stack.
static uint8_t advertising_set_handle = 0xff;

// Static variable to store request to sample hall sensor
// Request generated by GPIO interrupt on each BTN0 press
static bool hall_sensor_request;

// Static handle for the nvm3 object storing the latest hall sensor sample
static nvm3_ObjectKey_t sample_object_key = 0xA5A5;

// Static counter tracking how many hall sensor samples have been recorded
static uint32_t sample_count = 0;

typedef struct {
  float field_strength;
  uint32_t id;
  bool alert;
  bool tamper;
} hall_sensor_sample_t;

/**************************************************************************//**
 * Application Init.
 *****************************************************************************/
void app_init(void)
{
  hall_sensor_sample_t sample;

  // Load the last stored sensor sample
  Ecode_t err = nvm3_readData(nvm3_defaultHandle,
                              sample_object_key,
                              &sample,
                              sizeof(hall_sensor_sample_t));
  // If a previously stored sample was found, display it and update the count
  if (err == ECODE_NVM3_OK) {
    app_log("Stored Sample %lu\r\n"
            "  field_strength: %lu\r\n"
            "  alert: %u\r\n"
            "  tamper: %u\r\n\r\n",
            sample.id,
            (uint32_t) sample.field_strength,
            sample.alert,
            sample.tamper);
    // update count value
    sample_count = sample.id + 1;
  } else {
    app_log("Failed to find a previously stored sample.\r\n"
            "NVM3 Error 0x%lx returned.\r\n"
            "Check nvm3.h for details about specific error codes.\r\n\r\n",
            err);
  }

  // Enable and configure hall effect sensor
  sl_sensor_hall_init();

  // Configure FLASH_WRITE_INDICATOR and SLEEP_INDICATOR as a push pull output
  GPIO_PinModeSet(FLASH_WRITE_INDICATOR_PORT,
                  FLASH_WRITE_INDICATOR_PIN,
                  gpioModePushPull, 0);
  GPIO_PinModeSet(SLEEP_INDICATOR_PORT,
                  SLEEP_INDICATOR_PIN,
                  gpioModePushPull, 0);
}

/**************************************************************************//**
 * Application Process Action.
 *****************************************************************************/
void app_process_action(void)
{
  hall_sensor_sample_t sample;

  // Request is generated when BTN0 is pressed in app_request_hall_sensor
  if (hall_sensor_request) {
    // Clear request for next BTN0 press
    hall_sensor_request = false;

    // Increment sample id to keep track of how many samples have been taken
    sample.id = sample_count++;

    // Sample i2c and store data
    sl_sensor_hall_get(&sample.field_strength, &sample.alert, &sample.tamper);

    // Start GPIO high pulse for flash write duration
    GPIO_PinOutSet(FLASH_WRITE_INDICATOR_PORT,
                   FLASH_WRITE_INDICATOR_PIN);

    // Write field strength value to flash
    nvm3_writeData(nvm3_defaultHandle,
                   sample_object_key,
                   &sample,
                   sizeof(hall_sensor_sample_t));

    // End GPIO high pulse for flash write duration
    GPIO_PinOutClear(FLASH_WRITE_INDICATOR_PORT,
                     FLASH_WRITE_INDICATOR_PIN);

    // Report saved sensor sample to VCOM port
    app_log("New Sample %lu\r\n"
            "  field_strength: %lu\r\n"
            "  alert: %u\r\n"
            "  tamper: %u\r\n",
            sample.id,
            (uint32_t) sample.field_strength,
            sample.alert,
            sample.tamper);
  }
  // Start GPIO high pulse for sleep duration
  GPIO_PinOutSet(SLEEP_INDICATOR_PORT,
                 SLEEP_INDICATOR_PIN);
}

/**************************************************************************//**
 * Bluetooth stack event handler.
 * This overrides the dummy weak implementation.
 *
 * @param[in] evt Event coming from the Bluetooth stack.
 *****************************************************************************/
void sl_bt_on_event(sl_bt_msg_t *evt)
{
  sl_status_t sc;

  switch (SL_BT_MSG_ID(evt->header)) {
    // -------------------------------
    // This event indicates the device has started and the radio is ready.
    // Do not call any stack command before receiving this boot event!
    case sl_bt_evt_system_boot_id:
      // Create an advertising set.
      sc = sl_bt_advertiser_create_set(&advertising_set_handle);
      app_assert_status(sc);

      // Generate data for advertising
      sc = sl_bt_legacy_advertiser_generate_data(advertising_set_handle,
                                                 sl_bt_advertiser_general_discoverable);
      app_assert_status(sc);

      // Set advertising interval to 100ms.
      sc = sl_bt_advertiser_set_timing(
        advertising_set_handle,
        160, // min. adv. interval (milliseconds * 1.6)
        160, // max. adv. interval (milliseconds * 1.6)
        0,   // adv. duration
        0);  // max. num. adv. events
      app_assert_status(sc);
      // Start advertising and enable connections.
      sc = sl_bt_legacy_advertiser_start(advertising_set_handle,
                                         sl_bt_legacy_advertiser_connectable);
      app_assert_status(sc);
      break;

    // -------------------------------
    // This event indicates that a new connection was opened.
    case sl_bt_evt_connection_opened_id:
      break;

    // -------------------------------
    // This event indicates that a connection was closed.
    case sl_bt_evt_connection_closed_id:
      // Generate data for advertising
      sc = sl_bt_legacy_advertiser_generate_data(advertising_set_handle,
                                                 sl_bt_advertiser_general_discoverable);
      app_assert_status(sc);

      // Restart advertising after client has disconnected.
      sc = sl_bt_legacy_advertiser_start(advertising_set_handle,
                                         sl_bt_legacy_advertiser_connectable);
      app_assert_status(sc);
      break;

    // -------------------------------
    // Default event handler.
    default:
      break;
  }
}

/***************************************************************************//**
 * Simple Button
 * Button state changed callback
 * @param[in] handle Button event handle
 ******************************************************************************/
void sl_button_on_change(const sl_button_t *handle)
{
  if ((SL_SIMPLE_BUTTON_INSTANCE(0) == handle)
      && (sl_button_get_state(handle) == SL_SIMPLE_BUTTON_PRESSED)) {
    hall_sensor_request = true;
    // Start GPIO low pulse for wake duration
    GPIO_PinOutClear(SLEEP_INDICATOR_PORT,
                     SLEEP_INDICATOR_PIN);
  }
}
